# Generated by Django 3.1.5 on 2021-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expoAccepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expoToken',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
