# Generated by Django 3.1.5 on 2021-06-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210612_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expoAccepted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expoToken',
        ),
    ]
