# Generated by Django 3.1.5 on 2021-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporecord',
            name='expoToken',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
