# Generated by Django 3.1.5 on 2021-06-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0002_auto_20210612_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporecord',
            name='expoToken',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
