# Generated by Django 3.0.2 on 2020-01-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
        migrations.AlterModelTable(
            name='habit',
            table=None,
        ),
    ]
