# Generated by Django 3.0.2 on 2020-01-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.TextField(blank=True, max_length=255, unique=True),
        ),
    ]
