# Generated by Django 3.0.2 on 2020-01-30 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0003_auto_20200129_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habit',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True),
        ),
        migrations.CreateModel(
            name='HabitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='habits.Habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('habit', 'user')},
            },
        ),
        migrations.AddField(
            model_name='habit',
            name='members',
            field=models.ManyToManyField(through='habits.HabitMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
