# Generated by Django 3.0.2 on 2020-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20200130_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
