# Generated by Django 3.0.2 on 2020-01-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20200130_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='slug',
        ),
    ]
