# Generated by Django 3.0.2 on 2020-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20200130_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldstextfield'),
        ),
    ]
