# Generated by Django 3.0.2 on 2020-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
