# Generated by Django 3.0.2 on 2020-01-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_auto_20200130_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='slug',
        ),
    ]
