# Generated by Django 3.0.2 on 2020-01-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_habit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='slug',
        ),
    ]
