# Generated by Django 3.0.2 on 2020-01-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_remove_habit_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HabitMember',
        ),
    ]
