# Generated by Django 3.0.2 on 2020-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprofile',
            name='program',
            field=models.FileField(blank=True, default='efportal/user_programs/welcome.xlsx', upload_to='efportal/user_programs/'),
        ),
    ]
