# Generated by Django 3.0.2 on 2020-02-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200211_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentProfile',
        ),
    ]
