# Generated by Django 3.0.2 on 2020-03-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newsignup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewSignUp',
            new_name='NewProspect',
        ),
    ]
