# Generated by Django 3.0.2 on 2020-01-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200114_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default="{% static 'efportal/images/ef_logo.JPG'  %}", upload_to=''),
        ),
    ]
