# Generated by Django 3.0.2 on 2020-03-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200304_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProspect',
        ),
    ]
