# Generated by Django 3.0.2 on 2020-01-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200114_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='efportal/images/default.png', upload_to=''),
        ),
    ]
