# Generated by Django 3.0.2 on 2020-01-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200129_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='habit',
            field=models.TextField(max_length=265, null=True),
        ),
    ]
