# Generated by Django 3.0.2 on 2020-01-30 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200129_1659'),
        ('accounts', '0009_auto_20200129_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='habits.Habit'),
        ),
    ]
