# Generated by Django 3.0.2 on 2020-01-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200129_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='habit',
        ),
    ]
