# Generated by Django 3.0.2 on 2020-01-30 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20200129_1708'),
        ('accounts', '0011_remove_profile_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='habits.Habit'),
        ),
    ]
