# Generated by Django 3.0.2 on 2020-01-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20200130_0408'),
        ('accounts', '0013_auto_20200129_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='habit',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='habits.Habit'),
        ),
    ]
