# Generated by Django 3.0.2 on 2020-02-05 21:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20200205_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramDocument',
            new_name='DocumentProfile',
        ),
    ]
