# Generated by Django 3.0.2 on 2021-01-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitpost',
            name='username',
        ),
    ]
