# Generated by Django 3.1.5 on 2021-07-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitposts', '0002_remove_habitpost_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitpost',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
