# Generated by Django 3.0.2 on 2021-01-21 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_item_name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('weight_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('unit', models.CharField(default='lb', max_length=10)),
                ('created', models.DateTimeField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True)),
                ('weight_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightmeasurements', to='tracking.WeightRecord')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MaxMultipleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('max_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxMultipleMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('unit', models.CharField(default='lb', max_length=10)),
                ('created', models.DateField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True)),
                ('max_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_itementered', to='tracking.MaxListItem')),
                ('max_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxitemmeasurements', to='tracking.MaxMultipleRecord')),
            ],
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('habit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10)),
                ('created', models.DateTimeField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitsentered', to='habits.Habit')),
                ('habit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitmeasurements', to='tracking.HabitRecord')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
