# Generated by Django 3.0.2 on 2020-02-07 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('weight_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('unit', models.CharField(default='lb', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('weight_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to='tracking.WeightRecord')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
