# Generated by Django 3.0.2 on 2020-02-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200209_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmbacksquatmeasurement',
            old_name='rmbackquat',
            new_name='rmbacksquat',
        ),
        migrations.RenameField(
            model_name='rmbacksquatmeasurement',
            old_name='rmbackquat_record',
            new_name='rmbacksquat_record',
        ),
    ]
