# Generated by Django 3.0.2 on 2020-02-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200209_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmbacksquatmeasurement',
            name='rmbacksquat_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmbacksquatmeasurements', to='tracking.RMBackSquatRecord'),
        ),
    ]
