# Generated by Django 3.0.2 on 2020-02-10 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
        ('tracking', '0006_auto_20200209_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('habit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(choices=[(1, 'YES'), (2, 'NO')], max_length=10)),
                ('created', models.DateField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitsentered', to='habits.Habit')),
                ('habit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitmeasurements', to='tracking.RMBackSquatRecord')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
