# Generated by Django 3.0.2 on 2020-02-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_habitmeasurement_habitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmeasurement',
            name='reply',
            field=models.CharField(choices=[(1, 'YES'), (2, 'NO')], default=1, max_length=10),
        ),
    ]
