# Generated by Django 3.0.2 on 2020-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20200210_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmeasurement',
            name='reply',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10),
        ),
    ]
