# Generated by Django 3.0.2 on 2020-02-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20200210_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmeasurement',
            name='habit_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitmeasurements', to='tracking.HabitRecord'),
        ),
    ]
