# Generated by Django 3.0.2 on 2020-02-16 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0010_auto_20200210_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_item', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxMMultipleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('max_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxMultipleMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('created', models.DateField()),
                ('max_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_itementered', to='tracking.MaxListItem')),
                ('max_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxmeasurements', to='tracking.MaxMMultipleRecord')),
            ],
        ),
    ]
