# Generated by Django 3.0.2 on 2020-02-17 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0011_maxlistitem_maxmmultiplerecord_maxmultiplemeasurement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaxMMultipleRecord',
            new_name='MaxMultipleRecord',
        ),
    ]
