# Generated by Django 3.0.2 on 2020-02-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20200216_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxmultiplemeasurement',
            name='unit',
            field=models.CharField(default='lb', max_length=10),
        ),
    ]
