# Generated by Django 3.0.2 on 2020-02-17 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_maxmultiplemeasurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxlistitem',
            old_name='max_item',
            new_name='max_item_name',
        ),
        migrations.AlterField(
            model_name='maxmultiplemeasurement',
            name='max_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxitemmeasurements', to='tracking.MaxMultipleRecord'),
        ),
    ]
