# Generated by Django 3.0.2 on 2020-02-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_auto_20200216_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmbacksquatrecord',
            name='rmbacksquat_user',
        ),
        migrations.DeleteModel(
            name='RMBackSquatMeasurement',
        ),
        migrations.DeleteModel(
            name='RMBackSquatRecord',
        ),
    ]
