# Generated by Django 3.0.2 on 2020-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20200219_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightmeasurement',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
