# Generated by Django 3.0.2 on 2020-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_weightmeasurement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightmeasurement',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
