# Generated by Django 3.0.2 on 2020-04-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20200408_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightmeasurement',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
    ]
