# Generated by Django 3.0.2 on 2020-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20200408_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightmeasurement',
            name='slug',
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='created',
            field=models.DateField(unique=True),
        ),
    ]
