# Generated by Django 3.0.2 on 2020-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20200408_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightmeasurement',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='created',
            field=models.DateField(),
        ),
    ]
