# Generated by Django 3.0.2 on 2020-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_auto_20200408_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmeasurement',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='maxmultiplemeasurement',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
    ]
