# Generated by Django 3.0.2 on 2020-04-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_auto_20200408_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmeasurement',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='maxmultiplemeasurement',
            name='slug',
        ),
    ]
