# Generated by Django 3.0.2 on 2021-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_auto_20200408_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmeasurement',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maxmultiplemeasurement',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
